### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by firmai** [ga-group/bsym#3]
Hi, I love this project, but can't seem to access the data, and is the expectation that it updates every month? Thanks again.

**Comment by hroptatyr** [comment]
Hey Derek,
I don't want to be on-record with political issues here.  Let's say the choice of our hoster was suboptimal.

You're right, it's meant to be updated every month, the dump starts on the first Sunday of the month.

I shall ping you in private.

**Comment by firmai** [comment]
Hi @hroptatyr hope you are doing well, thanks again for these updates. I am using the data with good success, I think I will probably take the weekends over the year to get the NLP model up and running and then share it with you. 
![image](https://user-images.githubusercontent.com/26666267/188218481-66704274-2b32-428e-94e4-5e2e54835ea5.png)
![image](https://user-images.githubusercontent.com/26666267/188218577-fed61d72-ab51-4a5d-94fa-b8299596cd7e.png)
