### ISSUE TITLE
September 2022 FIRD gzip archive integrity check failing

### ISSUE THREAD

**Issue by davidandreoletti** [ga-group/bsym#4]
Hi @hroptatyr ,

FIRD dataset is rather large. After download, gzip's integrity check failed as follow:

```
gzip -t -v data.ga-group.nl_fird_2022-09-04.gz
gzip: data.ga-group.nl_fird_2022-09-04.gz: invalid compressed data--crc error
gzip: data.ga-group.nl_fird_2022-09-04.gz: invalid compressed data--length error
```

NOTE: The archive was downloaded 3 times and gzip integrity verified failed every time.

1. would you consider providing a **file checksum** (sha256?) along with the archive file ?

2. Would you consider verifying the current FIRD archive integrity with 'gzip -t filé' and report the result please ?

Env:
- Gzip v1.12 (2022 release)
- Alpine Linux 3.16

Note: The other archives for the same date (LEMP, FIMP, LERD) have successfully passed gzip's integrity check.

```
gzip -t -v /data/tmp/data.ga-group.nl_fimp_2022-09-04.nq.gz; gzip -t -v /data/tmp/data.ga-group.nl_lemp_2022-09-04.nq.gz; gzip -t -v /data/tmp/data.ga-group.nl_lerd_2022-09-04.nq.gz
/data/tmp/data.ga-group.nl_fimp_2022-09-04.nq.gz:        OK
/data/tmp/data.ga-group.nl_lemp_2022-09-04.nq.gz:        OK
/data/tmp/data.ga-group.nl_lerd_2022-09-04.nq.gz:        OK
```

**Comment by hroptatyr** [comment]
Hi David,
thanks for bringing this to my attention. I've just compared the current `data.ga-group.nl_fird_2022-10-02.nq.gz` on my local filesystem to the remote one.

The sha256 in both cases is `2e860d928991c7f2c677cb9090e53b8c63da5decfda6ad030365a623bf87d6f7`.

**Comment by davidandreoletti** [comment]
Thanks for the prompt response.

> data.ga-group.nl_fird_2022-10-02.nq.gz  [ ...] sha256 in both cases is 2e860d928991c7f2c677cb9090e53b8c63da5decfda6ad030365a623bf87d6f7

The README currently lists the 202-**09**-04 archives and not the 2022-**10**-02 archives you provided the checksum for. Will you share the Nov ones them early next month ?

**Comment by hroptatyr** [comment]
Sorry, I forgot to push the updates. Should all be resolved now.

**Comment by davidandreoletti** [comment]
> Sorry, I forgot to push the updates. Should all be resolved now.

Thank you. Will check the archives and close the issue once successfully verified.
